# https://cloud.google.com/appengine/docs/locations
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

endpoints_api_service:
  name: YOUR-PROJECT-ID.appspot.com
  config_id: "2017-07-03r1"
