apiVersion: v1
kind: Service
metadata:
  name: esp-echo
spec:
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: esp-echo
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: esp-echo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: esp-echo
    spec:
      containers:
      # [START esp]
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:1
        args: [
          "-p", "8081",
          "-a", "127.0.0.1:8080",
          "-s", "SERVICE_NAME",
          "-v", "SERVICE_CONFIG_ID",
        ]
      # [END esp]
        ports:
        - containerPort: 8081
      - name: echo
        image: gcr.io/google-samples/echo-python:1.0
        ports:
        - containerPort: 8080
